import Fastify from "fastify";
import fastifyStatic from "@fastify/static";
import type { AppConfig } from "./infrastructure/config.js";
import { logger, type AppLogger } from "./infrastructure/logger.js";
import { openDatabase } from "./infrastructure/database.js";
import { UuidV7Generator } from "./infrastructure/UuidV7Generator.js";
import { SystemClock } from "./ports/Clock.js";
import { SqliteSourceRepository } from "./adapters/outbound/persistence/SqliteSourceRepository.js";
import { SqliteContentRepository } from "./adapters/outbound/persistence/SqliteContentRepository.js";
import { SqliteCollectionRunRepository } from "./adapters/outbound/persistence/SqliteCollectionRunRepository.js";
import { SafeHttpFetcher } from "./adapters/outbound/http/SafeHttpFetcher.js";
import { FeedSourceAdapter } from "./adapters/outbound/collection/FeedSourceAdapter.js";
import { GenericHtmlSourceAdapter } from "./adapters/outbound/collection/GenericHtmlSourceAdapter.js";
import { AdapterRegistry } from "./adapters/outbound/collection/AdapterRegistry.js";
import { MetadataNormalizer } from "./adapters/outbound/metadata/MetadataNormalizer.js";
import { UrlCanonicalizer } from "./adapters/outbound/metadata/UrlCanonicalizer.js";
import { ContentIdentityService } from "./domain/services/ContentIdentityService.js";
import { TestSourceUseCase } from "./application/use-cases/TestSourceUseCase.js";
import { AddSourceUseCase } from "./application/use-cases/AddSourceUseCase.js";
import { UpdateSourceUseCase } from "./application/use-cases/UpdateSourceUseCase.js";
import { DeleteSourceUseCase } from "./application/use-cases/DeleteSourceUseCase.js";
import { CollectSourceUseCase } from "./application/use-cases/CollectSourceUseCase.js";
import { CollectDueSourcesUseCase } from "./application/use-cases/CollectDueSourcesUseCase.js";
import { ListContentUseCase } from "./application/use-cases/ListContentUseCase.js";
import { IntervalJobScheduler } from "./adapters/outbound/scheduling/IntervalJobScheduler.js";
import { sourceRoutes } from "./adapters/inbound/http/source-routes.js";
import { contentRoutes } from "./adapters/inbound/http/content-routes.js";
import { collectionRoutes } from "./adapters/inbound/http/collection-routes.js";

export async function buildApp(config:AppConfig,appLogger:AppLogger=logger){
  const app=Fastify({logger:false,bodyLimit:256*1024});const database=openDatabase(config.databasePath);const clock=new SystemClock();const ids=new UuidV7Generator();
  const sources=new SqliteSourceRepository(database);const content=new SqliteContentRepository(database);const runs=new SqliteCollectionRunRepository(database);const http=new SafeHttpFetcher(config.http);const registry=new AdapterRegistry([new FeedSourceAdapter(http),new GenericHtmlSourceAdapter(http)]);const normalizer=new MetadataNormalizer();const tester=new TestSourceUseCase(registry,normalizer,ids,clock);const add=new AddSourceUseCase(sources,ids,clock,tester);const update=new UpdateSourceUseCase(sources,clock,tester);const remove=new DeleteSourceUseCase(sources);const collect=new CollectSourceUseCase(sources,content,runs,registry,normalizer,new UrlCanonicalizer(),new ContentIdentityService(),ids,clock,config.failureThreshold);const list=new ListContentUseCase(content);const collectDue=new CollectDueSourcesUseCase(sources,collect,clock,appLogger);const scheduler=new IntervalJobScheduler(config.schedulerPollMs,error=>appLogger.error({error:error instanceof Error?error.message:String(error)},"Scheduler failed"));
  app.setErrorHandler((error,request,reply)=>{const failure=error instanceof Error?error:new Error("Request failed");const status=(error as {statusCode?:number}).statusCode??(failure.message.toLowerCase().includes("not found")?404:failure.message.toLowerCase().includes("already")?409:400);appLogger.warn({method:request.method,url:request.url,status,error:failure.message},"Request failed");reply.code(status).send({error:{code:status===404?"NOT_FOUND":status===409?"CONFLICT":"BAD_REQUEST",message:failure.message}});});
  app.get("/api/health",async()=>({status:"ok",collectionPaused:config.collectionPaused}));
  await sourceRoutes(app,{sources,add,update,remove,test:tester,collect});await contentRoutes(app,{content,list});await collectionRoutes(app,{runs});
  await app.register(fastifyStatic,{root:config.publicPath,prefix:"/"});
  app.addHook("onReady",async()=>{if(!config.collectionPaused)scheduler.start(()=>collectDue.execute());});
  app.addHook("onClose",async()=>{scheduler.stop();database.close();});
  return app;
}
